### ISSUE TITLE
about inference  time

### ISSUE THREAD

**Issue by suke27** [qinzheng93/diagonalwise-refactorization-tensorflow#1]
I found it is more complex than normal depth-wise ops. will it faster than normal depth-wise?

**Comment by ghost** [comment]
I have tested it with tf 0.12 and 0.13 on 1080Ti, and it is faster than the normal depth-wise conv. But for newer tf versions, I haven't tested.

**Comment by johnnylili** [comment]
你好，我从知乎上你的回答过来的。请问一下在tensorflow上实现group conv有什么好的优化方法吗？你的这个方法比起常规的分组卷积速度上能提高多少？

**Comment by atztao** [comment]
i think this should be update,because the new tnesorflow is not faster your code,but the code is last years.

**Comment by ghost** [comment]
Actually, for now, TensorFlow, PyTorch and MXNet have improved their implementation of depthwise convolutions and achieve very good efficiency. So maybe I won't update this repo anymore.

**Comment by atztao** [comment]
I agree with you.
